In [1]:
pip install numpy
pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
# Q.1 Yes, there is difference in the datatype of variables, list_ and array_list. Here is the code to print the data types of variables:

In [5]:
type(list_)  # type is used to find datatype.

list

In [6]:
type(array_list)

numpy.ndarray

In [7]:
# Q.2
for i in list_:
   data_type=type(i)
   print(data_type) # printing datatype of each element of list

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
for i in array_list:
   data_type=type(i)
   print(data_type)  # printing datatype of each element of array

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
# Q.3  Yes, there is difference in the datatypes of the elements of both the list_ and array_list variables.list_ is of str type and array_list is numpy.int64 type.

In [14]:
array_list = np.array(object = list_, dtype = int)

In [15]:
for i in array_list:
   data_type=type(i)
   print(data_type)

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
for i in list_:
   data_type=type(i)
   print(data_type)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
# Q.4

In [20]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
num_array.shape   # (i) shape function is used to get the row and column present in array.

(2, 3)

In [21]:
num_array.size  #(ii) size function is used to get the total no of elements in array.

6

In [22]:
# Q.5

In [23]:
arr=np.zeros((3,3))  # this is the 3d array containing zeros


In [24]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr.size

9

In [26]:
# Q.6

In [32]:
arr_1=np.eye(5,5)  # this is the identity matrix of shape (5,5)


In [33]:
arr_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr_1.shape

(5, 5)